#spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
#spring.datasource.url=jdbc:mysql://localhost:3306/store?serverTimezone=Europe/Moscow&allowPublicKeyRetrieval=true&useSSL=false
#spring.datasource.username=root
#spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver
#spring.datasource.username=
#spring.datasource.password=
spring.datasource.initialization-mode=always
#spring.datasource.password=
spring.jpa.hibernate.ddl-auto=update
#spring.jpa.database-platform=org.hibernate.dialect.MySQL5Dialect
#spring.jpa.properties.jdbc = UTC
logging.file.path=
server.port=8295
#debug=true


#spring.config.import=file:C:/Users/alexei/IdeaProjects/demo/src/main/resources/application.properties





